services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET=${SECRET}

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_PROD_API_URL=${REACT_APP_PROD_API_URL} # Make sure it's prefixed with REACT_APP_
    volumes:
      - ./client:/usr/src/app
    command: npm start
